scx: Make task_on_scx() take const task_struct
task_on_scx() takes a struct task_struct *p, but it's called by
__task_prio() in CONFIG_SCHED_CORE which takes a const struct
task_struct *. This can cause the build to fail due to incompatible
pointer types:

kernel/sched/core.c:170:18: error: passing 'const struct task_struct *' to parameter of type 'struct task_struct *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        if (task_on_scx(p))
                        ^
kernel/sched/ext.h:124:52: note: passing argument to parameter 'p' here
static inline bool task_on_scx(struct task_struct *p)

Fix task_on_scx() so this doesn't happen.

Signed-off-by: David Vernet <void@manifault.com>